# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Felfa"
description: > # this means to ignore newlines until "email:"
   Software libre, 8 bits, diseño gráfico y otras cavilaciones

#email: nomail@nomail
#blog logo
logo: "/assets/images/felfalogo.png"
# blog cover
cover: "/assets/images/header.gif"

name: 'Felfa'
author: 'Felfalido'
author_image: "/assets/images/da404d8ca0775d0e4d95.png"

paginate:	5

url: "https://felfa.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: '@'

#fill in disqus shortname to use disqus
disqus: felfa-github-io

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://quitter.es/felfa
    desc: Quitter
    share_url: http://quitter.es/felfa
    share_title: 
    share_link: 

  - icon:	facebook
    url:	https://diasp.org/people/c28ab5d0787d01342e86782bcb452bd5
    desc: Diaspora*
    share_url: 
    share_title: 
    share_link: 

  - icon:	github
    url:	https://github.com/felfa
    desc:	GitHub
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
